// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jldblrzozemymzsbzohi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsZGJscnpvemVteW16c2J6b2hpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTM4MDEsImV4cCI6MjA2MzM4OTgwMX0.nnbAeRft7NBxXYRt384tXUlxS4IPaiubPaY2J0nuZ5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);